### ISSUE TITLE
已搭建，暂无BUG，能否加入wxid验证

### ISSUE THREAD

**Issue by penhuowa** [GeekinGH/AiChatHelperNodejs#1]
感谢大佬已搭建成功，怕被人白嫖接口怎么搞QAQ

**Comment by penhuowa** [comment]
能否加入wxid校验

**Comment by GeekinGH** [comment]
有这个功能的，index.js文件中，
// 授权的微信ID
const WXID_ARRAY = [wxid1,wxid2,wxid3,wxid4];

**Comment by GeekinGH** [comment]
我在readme中增加了这方面的详细说明了
